export const api = [
  {
    id: 1,
    name: 'The Willows',
    direction: '3517 W. Gray St. Utica',
    rooms: 3,
    bathrooms: 2,
    surface: '230 ft',
    montlhyCost: '$420/m',
    score: 4.7,
    img: require('../imgs/house1.jpg'),
  },
  {
    id: 2,
    name: 'Orchard House',
    direction: '120 Vegas Boulevard',
    rooms: 2,
    bathrooms: 1,
    surface: '240 ft',
    montlhyCost: '$460/m',
    score: 4.5,
    img: require('../imgs/house2.jpg'),
  },
  {
    id: 3,
    name: 'The Magic House',
    direction: '420 Music Row',
    rooms: 4,
    bathrooms: 3,
    surface: '250 ft',
    montlhyCost: '$450/m',
    score: 4.8,
    img: require('../imgs/house3.jpg'),
  },
  {
    id: 4,
    name: 'The King House',
    direction: '680 Wall Street',
    rooms: 5,
    bathrooms: 5,
    surface: '280 ft',
    montlhyCost: '$620/m',
    score: 5.0,
    img: require('../imgs/house4.jpg'),
  },
  {
    id: 5,
    name: 'The Big House',
    direction: '1492 5th. Avenue',
    rooms: 4,
    bathrooms: 6,
    surface: '245 ft',
    montlhyCost: '$550/m',
    score: 4.9,
    img: require('../imgs/house5.jpg'),
  },
];
