export const api = [
  {
    id: 1,
    name: 'The Willows',
    direction: '3517 W. Gray St. Utica',
    rooms: 3,
    bathrooms: 2,
    surface: 230,
    montlhyCost: 440,
    score: 4.7,
  },
  {
    id: 2,
    name: 'Orchard House',
    direction: '3518 W. Gray St. Utica',
    rooms: 2,
    bathrooms: 1,
    surface: 240,
    montlhyCost: 460,
    score: 4.5,
  },
  {
    id: 3,
    name: 'The Magic House',
    direction: '3519 W. Gray St. Utica',
    rooms: 4,
    bathrooms: 3,
    surface: 250,
    montlhyCost: 450,
    score: 4.8,
  },
  {
    id: 4,
    name: 'The King House',
    direction: '3520 W. Gray St. Utica',
    rooms: 5,
    bathrooms: 5,
    surface: 280,
    montlhyCost: 600,
    score: 5.0,
  },
  {
    id: 5,
    name: 'The Big House',
    direction: '3521 W. Gray St. Utica',
    rooms: 4,
    bathrooms: 6,
    surface: 245,
    montlhyCost: 510,
    score: 4.9,
  },
];
